import { describe, expect, it } from 'vitest';
import { z } from 'zod';
import { describeSchema, toEnvExample, toMarkdownDocs } from '../src/cli/describe.js';

describe('break: describe zod wrappers', () => {
  it('nullable/catch/brand unwrap to the inner type', () => {
    const s = z.object({
      n: z.string().nullable(),
      c: z.string().catch('fallback'),
      b: z.string().brand<'X'>(),
      r: z.string().readonly(),
    });
    const { fields, bestEffort } = describeSchema(s);
    expect(bestEffort).toBe(false);
    const byPath = Object.fromEntries(fields.map((f) => [f.path, f]));
    expect(byPath['n']?.type).toBe('string');
    expect(byPath['n']?.required).toBe(true); // nullable widens, does not optionalize
    expect(byPath['c']?.type).toBe('string');
    expect(byPath['b']?.type).toBe('string');
    expect(byPath['r']?.type).toBe('string');
  });

  it('empty object is complete (zero fields), not best-effort', () => {
    expect(describeSchema(z.object({}))).toEqual({ fields: [], bestEffort: false });
    expect(toEnvExample([])).toContain('# Generated by typed-settings gen');
  });

  it('Zod3-shaped fakes traverse the legacy path', () => {
    const leaf = (typeName: string, extra: Record<string, unknown> = {}) => ({ _def: { typeName, ...extra } });
    const schema = {
      _def: {
        typeName: 'ZodObject',
        shape: {
          opt: { _def: { typeName: 'ZodOptional', innerType: leaf('ZodString') } },
          nul: { _def: { typeName: 'ZodNullable', innerType: leaf('ZodNumber') } },
          dflt: { _def: { typeName: 'ZodDefault', defaultValue: 5, innerType: leaf('ZodNumber') } },
          ro: { _def: { typeName: 'ZodReadonly', innerType: leaf('ZodBoolean') } },
          en: { _def: { typeName: 'ZodEnum', values: ['a', 'b'] } },
          lit: { _def: { typeName: 'ZodLiteral' } },
          uni: { _def: { typeName: 'ZodUnion' } },
          unk: { _def: { typeName: 'ZodWeird' } },
        },
      },
    };
    const { fields, bestEffort } = describeSchema(schema);
    expect(bestEffort).toBe(false);
    const byPath = Object.fromEntries(fields.map((f) => [f.path, f]));
    expect(byPath['opt']).toMatchObject({ type: 'string', required: false });
    expect(byPath['nul']?.type).toBe('number');
    expect(byPath['dflt']).toMatchObject({ required: false, default: 5 });
    expect(byPath['en']?.type).toBe('enum(a|b)');
    expect(byPath['lit']?.type).toBe('literal');
    expect(byPath['uni']?.type).toBe('union');
    expect(byPath['unk']?.type).toBe('string'); // unknown legacy types degrade to string
  });

  it('function defaults and throwing helpers are contained', () => {
    const schema = {
      shape: {
        f: { type: 'default', def: { defaultValue: () => 'dyn', innerType: { type: 'string' } } },
        g: {
          type: 'optional',
          def: undefined,
          unwrap: () => ({ type: 'string' }),
        },
        h: {
          type: 'optional',
          def: undefined,
          unwrap: () => {
            throw new Error('nope');
          },
        },
      },
    };
    const { fields } = describeSchema(schema);
    const byPath = Object.fromEntries(fields.map((f) => [f.path, f]));
    expect(byPath['f']?.default).toBe('dyn');
    expect(byPath['g']?.type).toBe('string');
    expect(byPath['h']).toBeDefined();
  });

  it('shape as a throwing function falls through gracefully', () => {
    const schema = {
      get shape(): Record<string, unknown> {
        throw new Error('shape boom');
      },
    };
    expect(describeSchema(schema).bestEffort).toBe(true);
    // Same for a shape FUNCTION that throws when invoked (not just a throwing getter).
    const fnThrows = {
      shape: () => {
        throw new Error('shape fn boom');
      },
    };
    expect(describeSchema(fnThrows).bestEffort).toBe(true);
  });

  it('shape as a working function is walked', () => {
    const schema = {
      shape: () => ({ q: { type: 'string' } }),
    };
    const { fields, bestEffort } = describeSchema(schema);
    expect(bestEffort).toBe(false);
    expect(fields.map((f) => f.path)).toContain('q');
  });

  it('legacy _def.shape functions resolve or fall through', () => {
    const ok = { _def: { shape: () => ({ w: { _def: { typeName: 'ZodString' } } }) } };
    expect(describeSchema(ok).fields.map((f) => f.path)).toContain('w');
    const bad = {
      _def: {
        shape: () => {
          throw new Error('shape boom');
        },
      },
    };
    expect(describeSchema(bad).bestEffort).toBe(true);
  });

  it('throwing detectors degrade to best-effort instead of crashing', () => {
    const evil = new Proxy(
      {},
      {
        get() {
          throw new Error('trap boom');
        },
      },
    );
    expect(describeSchema(evil).bestEffort).toBe(true);
  });

  it('transparent wrappers (readonly/nonoptional/success) unwrap with innerType', () => {
    for (const t of ['readonly', 'nonoptional', 'success']) {
      const schema = { shape: { f: { type: t, def: { innerType: { type: 'number' } } } } };
      const { fields } = describeSchema(schema);
      expect(fields.find((f) => f.path === 'f')?.type, t).toBe('number');
    }
  });

  it('throwing Zod3 default factories are contained', () => {
    const schema = {
      _def: {
        typeName: 'ZodObject',
        shape: {
          f: {
            _def: {
              typeName: 'ZodDefault',
              defaultValue: () => {
                throw new Error('default boom');
              },
              innerType: { _def: { typeName: 'ZodString' } },
            },
          },
        },
      },
    };
    const { fields } = describeSchema(schema);
    expect(fields.find((f) => f.path === 'f')).toMatchObject({ type: 'string', required: false });
  });
});

describe('break: describe valibot variants', () => {
  it('nullable/non_optional/unknown wrappers and scalar kinds', () => {
    const str = { type: 'string' };
    const schema = {
      type: 'object',
      entries: {
        a: { type: 'nullable', wrapped: str },
        b: { type: 'non_optional', wrapped: str },
        c: { type: 'nullish', wrapped: str },
        d: { type: 'bigint' },
        e: { type: 'date' },
        f: { type: 'record' },
        g: { type: 'tuple' },
        h: { type: 'enum_', options: ['x'] },
        i: { type: 'literal', literal: 1 },
        j: { type: 'union' },
        k: { type: 'nan' },
        l: { type: 'something-new' },
        m: { type: 'optional' }, // optional without wrapped/default
      },
    };
    const { fields, bestEffort } = describeSchema(schema);
    expect(bestEffort).toBe(false);
    const byPath = Object.fromEntries(fields.map((f) => [f.path, f]));
    expect(byPath['a']).toMatchObject({ type: 'string', required: true });
    expect(byPath['c']?.required).toBe(false);
    expect(byPath['d']?.type).toBe('bigint');
    expect(byPath['h']?.type).toContain('enum');
    expect(byPath['i']?.type).toContain('literal');
    expect(byPath['l']?.type).toBe('something-new');
    expect(byPath['m']?.required).toBe(false);
  });
});

describe('break: describe arktype method-json and nesting', () => {
  it('json() as a method (or throwing) is handled', () => {
    const methodForm = {
      json: () => ({ domain: 'object', required: [{ key: 'p', value: 'number' }], optional: [] }),
    };
    expect(describeSchema(methodForm).bestEffort).toBe(false);
    const throwing = {
      json: () => {
        throw new Error('json boom');
      },
    };
    expect(describeSchema(throwing).bestEffort).toBe(true);
  });

  it('nested objects recurse; unions report union', () => {
    const schema = {
      json: { domain: 'object', required: [{ key: 'db', value: { domain: 'object', required: [{ key: 'h', value: 'string' }], optional: [] } }], optional: [] },
    };
    const { fields } = describeSchema(schema);
    expect(fields.map((f) => f.path)).toContain('db.h');
    const union = { json: { domain: 'object', required: [{ key: 'u', value: ['a', 'b'] }], optional: [] } };
    expect(describeSchema(union).fields[0]?.type).toBe('union');
    const seq = { json: { domain: 'object', required: [{ key: 't', value: { sequence: 'string', proto: 'Array' } }], optional: [] } };
    expect(describeSchema(seq).fields[0]?.type).toBe('array');
    // A non-object json root is not a settings object — best-effort placeholder.
    const scalar = { json: 'string' };
    expect(describeSchema(scalar).bestEffort).toBe(true);
    // A bare object-domain node with no entries degrades to a root field (pinned).
    expect(describeSchema({ json: { domain: 'object' } })).toEqual({
      fields: [{ path: '<root>', type: 'object', required: true, default: undefined }],
      bestEffort: false,
    });
  });

  it('odd type nodes degrade without crashing', () => {
    const schema = {
      json: {
        domain: 'object',
        required: [
          { key: 'p', value: { proto: 42 } },
          { key: 'n', value: 5 },
        ],
        optional: [],
      },
    };
    const { fields } = describeSchema(schema);
    expect(fields.find((f) => f.path === 'p')?.type).toBe('string');
    expect(fields.find((f) => f.path === 'n')?.type).toBe('string');
  });
});

describe('break: emitters skip the <root> placeholder', () => {
  it('toEnvExample never emits <ROOT>=', () => {
    const out = toEnvExample([{ path: '<root>', type: 'string', required: false, description: 'GEN_BEST_EFFORT: x' }]);
    expect(out).not.toMatch(/<ROOT>=/);
    expect(out).toContain('GEN_BEST_EFFORT');
  });

  it('toMarkdownDocs renders the field table', () => {
    const md = toMarkdownDocs([
      { path: 'port', type: 'number', required: false, default: 3000 },
      { path: 'db.host', type: 'string', required: true },
    ]);
    expect(md).toContain('| `PORT` | `port` | number | false | `3000` |');
    expect(md).toContain('| `DB__HOST` | `db.host` | string | true | - |');
  });
});
